

SELECT *, NOME AS NOME_COMPLETO FROM USUARIOS WHERE IDADE >=30;


SELECT NOME || '-' ||EMAIL AS NOME_EMAIL FROM USUARIOS;

SELECT CONCAT(NOME, '-', EMAIL, '-', IDADE) AS NOME_EMAIL FROM USUARIOS;


SELECT ROUND(AVG(IDADE), 2) FROM usuarios;


-- NUMERO MINIMO E MAXIMO

SELECT MIN(IDADE)FROM USUARIOS;
SELECT MIN(CADASTRO)FROM USUARIOS;
SELECT MAX(IDADE) FROM USUARIOS;
SELECT MAX(CADASTRO)FROM USUARIOS;

-- FUNÇÃO PARA SOMAR

SELECT SUM(IDADE) FROM usuarios;

-- CONVERTER TIPO DE DADOS


SELECT IDADE::TEXT FROM usuarios;
SELECT CAST(IDADE AS TEXT) FROM usuarios;

